"""Public type models: send parameters, the send response, and webhook events."""

from __future__ import annotations

from .events import (
    ClickContext,
    ClickedData,
    DelayedData,
    DeliveredData,
    DeliveryContext,
    DomainStatusData,
    DomainStatusEvent,
    EmailBouncedEvent,
    EmailClickedEvent,
    EmailDeliveredEvent,
    EmailDeliveryDelayedEvent,
    EmailOpenedEvent,
    EmailSuppressedEvent,
    EngagementContext,
    FailureContext,
    MessageContext,
    OpenedData,
    SuppressedData,
    SuppressionContext,
    UnknownEvent,
    WebhookEvent,
    WebhookStatusData,
    WebhookStatusEvent,
)
from .params import Attachment, Recipients, SendEmailParams, Tag
from .responses import Email

__all__ = [
    "Attachment",
    "ClickContext",
    "ClickedData",
    "DelayedData",
    "DeliveredData",
    "DeliveryContext",
    "DomainStatusData",
    "DomainStatusEvent",
    "Email",
    "EmailBouncedEvent",
    "EmailClickedEvent",
    "EmailDeliveredEvent",
    "EmailDeliveryDelayedEvent",
    "EmailOpenedEvent",
    "EmailSuppressedEvent",
    "EngagementContext",
    "FailureContext",
    "MessageContext",
    "OpenedData",
    "Recipients",
    "SendEmailParams",
    "SuppressedData",
    "SuppressionContext",
    "Tag",
    "UnknownEvent",
    "WebhookEvent",
    "WebhookStatusData",
    "WebhookStatusEvent",
]
