"""Public type models: send parameters, the send response, and webhook events."""

from __future__ import annotations

from .events import (
    ClickContext,
    ClickedData,
    DelayedData,
    DeliveredData,
    DeliveryContext,
    DomainStatusData,
    DomainStatusEvent,
    EmailBouncedEvent,
    EmailClickedEvent,
    EmailDeliveredEvent,
    EmailDeliveryDelayedEvent,
    EmailOpenedEvent,
    EmailSuppressedEvent,
    EngagementContext,
    FailureContext,
    MessageContext,
    OpenedData,
    SuppressedData,
    SuppressionContext,
    UnknownEvent,
    WebhookEvent,
    WebhookStatusData,
    WebhookStatusEvent,
)
from .params import (
    Attachment,
    Recipients,
    ScheduledEmailBatchUpdateParams,
    ScheduledEmailListParams,
    ScheduledEmailUpdateParams,
    SendEmailParams,
    Tag,
)
from .responses import (
    CanceledScheduledEmail,
    Email,
    PageSteps,
    Pagination,
    ScheduledEmail,
    ScheduledEmailBatchCancel,
    ScheduledEmailBatchUpdate,
    ScheduledEmailPage,
)

__all__ = [
    "Attachment",
    "CanceledScheduledEmail",
    "ClickContext",
    "ClickedData",
    "DelayedData",
    "DeliveredData",
    "DeliveryContext",
    "DomainStatusData",
    "DomainStatusEvent",
    "Email",
    "EmailBouncedEvent",
    "EmailClickedEvent",
    "EmailDeliveredEvent",
    "EmailDeliveryDelayedEvent",
    "EmailOpenedEvent",
    "EmailSuppressedEvent",
    "EngagementContext",
    "FailureContext",
    "MessageContext",
    "OpenedData",
    "PageSteps",
    "Pagination",
    "Recipients",
    "ScheduledEmail",
    "ScheduledEmailBatchCancel",
    "ScheduledEmailBatchUpdate",
    "ScheduledEmailBatchUpdateParams",
    "ScheduledEmailListParams",
    "ScheduledEmailPage",
    "ScheduledEmailUpdateParams",
    "SendEmailParams",
    "SuppressedData",
    "SuppressionContext",
    "Tag",
    "UnknownEvent",
    "WebhookEvent",
    "WebhookStatusData",
    "WebhookStatusEvent",
]
